import {FeedbackType} from '../interfaces/feedbackType';

export const feedbackList: FeedbackType[] = 
[
    { 
            level:'Level0'
            ,levelName:'Telephonic'
            ,interviewerName:'sree'
            ,jobId:'Test098'
            ,feedback:'Confident at the skill'
            ,rating:4
            ,sno:1
    },
    { 
        level:'Level1'
        ,levelName:'F2F'
        ,interviewerName:'sree'
        ,jobId:'Test098'
        ,feedback:'Very good'
        ,rating:5
        ,sno:1
},
{ 
    level:'Level0'
    ,levelName:'Telephonic'
    ,interviewerName:'John'
    ,jobId:'UIDev002'
    ,feedback:'Good'
    ,rating:3
    ,sno:3
},
{ 
    level:'Level1'
    ,levelName:'F2F'
    ,interviewerName:'sree'
    ,jobId:'UIDev002'
    ,feedback:'Very Good'
    ,rating:5
    ,sno:3
},
{ 
    level:'Level2'
    ,levelName:'F2FL-2'
    ,interviewerName:'Kristin'
    ,jobId:'UIDev002'
    ,feedback:'Good'
    ,rating:3
    ,sno:3
},
{ 
    level:'Level0'
    ,levelName:'Telephonic'
    ,interviewerName:'Khan'
    ,jobId:'SysDEV002'
    ,feedback:'Good'
    ,rating:4
    ,sno:2
},
{ 
    level:'Level1'
    ,levelName:'F2F'
    ,interviewerName:'Sree'
    ,jobId:'SysDEV002'
    ,feedback:'Good'
    ,rating:4
    ,sno:2
},
{ 
    level:'Level0'
    ,levelName:'Telephonic'
    ,interviewerName:'sree'
    ,jobId:'SysTest01'
    ,feedback:'Good'
    ,rating:5
    ,sno:4
},
{ 
    level:'Level1'
    ,levelName:'F2F'
    ,interviewerName:'Khan'
    ,jobId:'SysTest01'
    ,feedback:'Good'
    ,rating:5
    ,sno:4
},
{ 
    level:'Level0'
    ,levelName:'Telephonic'
    ,interviewerName:'Raj'
    ,jobId:'Test009'
    ,feedback:'Very Good'
    ,rating:5
    ,sno:5
},
{ 
    level:'Level1'
    ,levelName:'F2F'
    ,interviewerName:'Ram'
    ,jobId:'Test009'
    ,feedback:'Good'
    ,rating:4
    ,sno:5
},
{ 
    level:'Level2'
    ,levelName:'F2FL2'
    ,interviewerName:'Khan'
    ,jobId:'Test009'
    ,feedback:'Good'
    ,rating:5
    ,sno:5
},
{ 
    level:'Level3'
    ,levelName:'F2FL3'
    ,interviewerName:'sree'
    ,jobId:'Test009'
    ,feedback:'Fantastic'
    ,rating:5
    ,sno:5
},
{ 
    level:'Level4'
    ,levelName:'F2FHR'
    ,interviewerName:'Kalpana'
    ,jobId:'Test010'
    ,feedback:'Selected , to be offered soon'
    ,rating:5
    ,sno:5
},
{ 
    level:'Level0'
    ,levelName:'Telephonic'
    ,interviewerName:'sree'
    ,jobId:'sdfsf'
    ,feedback:'Good'
    ,rating:5
    ,sno:6
},
{ 
    level:'Level1'
    ,levelName:'F2F'
    ,interviewerName:'Khan'
    ,jobId:'sdfsf'
    ,feedback:'Good'
    ,rating:5
    ,sno:6
},
{ 
    level:'Level0'
    ,levelName:'Telephonic'
    ,interviewerName:'sree'
    ,jobId:'asfsdf'
    ,feedback:'Good'
    ,rating:5
    ,sno:7
},
{ 
    level:'Level1'
    ,levelName:'F2F'
    ,interviewerName:'Khan'
    ,jobId:'asfsdf'
    ,feedback:'Good'
    ,rating:3
    ,sno:7
},
{ 
    level:'Level2'
    ,levelName:'F2F'
    ,interviewerName:'John'
    ,jobId:'asfsdf'
    ,feedback:'Good'
    ,rating:5
    ,sno:7
},
{ 
     level:'Level0'
    ,levelName:'Telephonic'
    ,interviewerName:'Ram'
    ,jobId:'UIDev001'
    ,feedback:'Very good'
    ,rating:4
    ,sno:8
},
{ 
    level:'Level1'
    ,levelName:'F2F01'
    ,interviewerName:'Khan'
    ,jobId:'UIDev001'
    ,feedback:'Good'
    ,rating:4
    ,sno:8
},
{ 
    level:'Level2'
    ,levelName:'F2F02'
    ,interviewerName:'John'
    ,jobId:'UIDev002'
    ,feedback:'Good'
    ,rating:4
    ,sno:8
},
{ 
    level:'Level3'
    ,levelName:'F2F03'
    ,interviewerName:'Jack'
    ,jobId:'UIDev002'
    ,feedback:'Fantastic'
    ,rating:4
    ,sno:8
},
]